[package]
name = "client"
version = "0.1.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
rust-version = "1.65"
description = "Client for the lightrider game"
readme = "README.md"
repository = "https://github.com/cBournhonesque/lightrider"
keywords = ["bevy", "multiplayer", "networking", "netcode", "gamedev"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
publish = false


[dependencies]
shared = { path = "../shared" }
lightyear = { git = "https://github.com/cBournhonesque/lightyear", branch = "main", features = [
    "webtransport",
    "websocket",
    "render",
] }
leafwing-input-manager = "0.11.2"
serde = { version = "1.0.188", features = ["derive"] }
anyhow = { version = "1.0.75", features = [] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
bevy = { version = "0.12", features = ["bevy_core_pipeline"] }
derive_more = { version = "0.99", features = ["add", "mul"] }
rand = "0.8.1"
clap = { version = "4.4", features = ["derive"] }
mock_instant = "0.3"
metrics-exporter-prometheus = { version = "0.13.0", optional = true }
bevy-inspector-egui = "0.22.1"
cfg-if = "1.0.0"

[target."cfg(not(target_family = \"wasm\"))".dependencies]
tokio = { version = "1.34", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
] }

[target."cfg(target_family = \"wasm\")".dependencies]
tokio = { version = "1.34", features = ["rt"] }
