[workspace]
resolver = "2"
members = [
  "client",
  "server",
  "shared",
]

[workspace.dependencies]
lightyear = { version = "0.26.4", features = [
  "input_bei",
  "frame_interpolation",
  "netcode",
  "webtransport",
  "webtransport_self_signed",
  "webtransport_dangerous_configuration",
  "debug",
] }
bevy_enhanced_input = { version = "0.22", features = ["serialize"] }
serde = { version = "1.0.188", features = ["derive"] }
ron = "0.8"
anyhow = { version = "1.0.75", features = [] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
bevy = { version = "0.18", features = ["bevy_core_pipeline"] }
derive_more = { version = "0.99", features = ["add", "mul"] }
clap = { version = "4.4", features = ["derive"] }
bevy_turborand = "0.13"
bevy-inspector-egui = "0.36"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
