FROM rustlang/rust:nightly-bookworm AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        clang \
        libasound2-dev \
        libudev-dev \
        libwayland-dev \
        libx11-dev \
        libxcursor-dev \
        libxi-dev \
        libxinerama-dev \
        libxkbcommon-dev \
        libxrandr-dev \
        pkg-config && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src/lightrider
COPY lightyear /src/lightyear
COPY bevygap /src/bevygap
COPY lightrider /src/lightrider

RUN CARGO_INCREMENTAL=0 cargo build --release -j 2 -p server --features bevygap --bin lightrider-server && \
    cp /src/lightrider/target/release/lightrider-server /tmp/lightrider-server && \
    rm -rf /src/lightrider/target /usr/local/cargo/git /usr/local/cargo/registry

FROM debian:bookworm-slim AS runtime

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        libasound2 \
        libudev1 \
        libwayland-client0 \
        libx11-6 \
        libxcursor1 \
        libxi6 \
        libxinerama1 \
        libxkbcommon0 \
        libxrandr2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /tmp/lightrider-server /app/lightrider-server
COPY lightrider/config/default.ron /app/config/default.ron
COPY lightrider/tools/server-container-entrypoint.sh /app/server-container-entrypoint.sh

EXPOSE 7777/udp

ENTRYPOINT ["/app/server-container-entrypoint.sh"]
